apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dust-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: dust-kube-ingress-ip-address
    networking.gke.io/managed-certificates: front-edge-managed-cert,connectors-edge-managed-cert,blog-managed-cert,docs-managed-cert
    networking.gke.io/v1beta1.FrontendConfig: "dust-frontendconfig"
    kubernetes.io/ingress.class: "gce"

spec:
  rules:
    - host: dust.tt
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: front-service
                port:
                  number: 80

    - host: front-edge.dust.tt
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: front-edge-service
                port:
                  number: 80

    - host: connectors-edge.dust.tt
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: connectors-edge-service
                port:
                  number: 80

    - host: blog.dust.tt
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: blog-service
                port:
                  number: 80

    - host: docs.dust.tt
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: docs-service
                port:
                  number: 80
