apiVersion: apps/v1
kind: Deployment
metadata:
  name: connectors-worker-notion-gc-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: connectors-worker
      worker: notion-gc
  template:
    metadata:
      labels:
        app: connectors-worker
        name: connectors-worker-pod
        worker: notion-gc
        admission.datadoghq.com/enabled: "true"
      annotations:
        ad.datadoghq.com/web.logs: '[{"source": "connectors-worker","service": "connectors-worker","tags": ["env:prod"]}]'
    spec:
      containers:
        - name: web
          image: gcr.io/or1g1n-186209/connectors-image:latest
          command: ["npm", "run", "start:worker"]
          args: ["--", "--workers", "notion_garbage_collector"]
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: connectors-worker-specific-config
            - secretRef:
                name: connectors-secrets
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP

          volumeMounts:
            - name: cert-volume
              mountPath: /etc/certs
            - name: private-key-volume
              mountPath: /etc/private-keys

          resources:
            requests:
              cpu: 2000m
              memory: 4Gi

            limits:
              cpu: 2000m
              memory: 4Gi

      volumes:
        - name: cert-volume
          secret:
            secretName: temporal-cert

        - name: private-key-volume
          secret:
            secretName: github-app-private-key
