apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
        name: front-pod
        admission.datadoghq.com/enabled: "true"
      annotations:
        ad.datadoghq.com/web.logs: '[{"source": "front","service": "front","tags": ["env:prod"]}]'
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: web
          image: gcr.io/or1g1n-186209/front-image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5

          envFrom:
            - configMapRef:
                name: front-config
            - secretRef:
                name: front-secrets
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP

            - name: PRESTOP_SECRET
              valueFrom:
                secretKeyRef:
                  name: prestop-secret
                  key: PRESTOP_SECRET

          volumeMounts:
            - name: cert-volume
              mountPath: /etc/certs
            - name: service-account-volume
              mountPath: /etc/service-accounts

          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "admin/prestop.sh"]

          resources:
            requests:
              # 1000m for nodejs (mono-threaded) + 500m to absorb spikes from contaner
              cpu: 1500m
              memory: 1.5Gi

            limits:
              cpu: 1500m
              memory: 1.5Gi

      volumes:
        - name: cert-volume
          secret:
            secretName: temporal-front-cert
        - name: service-account-volume
          secret:
            secretName: gcp-service-account-secret
