name: Lint & Build & Test (connectors)

on:
  push:
    paths:
      - sdks/js/**
      - connectors/**
      - .github/workflows/build-and-lint-connectors.yml

permissions:
  contents: read
  pull-requests: write

jobs:
  check-package-lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.13.0
      - name: Check package.json and package-lock.json sync
        run: ./scripts/check-package-lock-sync.sh connectors sdks/js
  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node Dependencies
        uses: ./.github/actions/setup-node-deps
      - name: Typecheck
        working-directory: connectors
        run: npm run tsgo -- --version && npm run tsgo
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node Dependencies
        uses: ./.github/actions/setup-node-deps
      - name: Lint and format:check
        working-directory: connectors
        run: npm run lint && npm run format:check
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node Dependencies
        uses: ./.github/actions/setup-node-deps
      - name: Install Postgres
        uses: dust-tt/postgresql-action@6730e69fe23f4f2989c19edf9e6e0d7ffeb0a05c
        with:
          postgresql docker image: mirror.gcr.io/postgres
          postgresql version: "14.13"
          postgresql db: connectors_test
          postgresql user: test
          postgresql password: test
          postgresql port: 5433
      - name: Run Tests
        working-directory: connectors
        env:
          CONNECTORS_DATABASE_URI: "postgres://test:test@localhost:5433/connectors_test"
          NODE_ENV: test
        run: npx tsx src/admin/db.ts && npm run test:ci
      - name: Build Tests Report
        if: always()
        uses: mikepenz/action-junit-report@v5
        with:
          report_paths: "**/connectors/junit*.xml"
          detailed_summary: true
          flaky_summary: true
          group_suite: true
          check_name: Tests Report
      - name: Knip
        uses: ./.github/actions/knip
        with:
          working_directory: connectors
