name: Publish SDK Client

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  id-token: write

concurrency:
  group: publish_sdk_client
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    # This ensures the workflow only runs on main branch
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
          cache-dependency-path: ./package-lock.json
          registry-url: "https://registry.npmjs.org"

      - name: Upgrade npm for OIDC support
        run: npm install -g npm@latest

      - name: Install root dependencies
        run: npm ci -w sdks/js

      - name: Build SDK
        working-directory: sdks/js
        run: npm run build

        # Needed because with bundleDependencies, npm workspace won't install the package
      - name: Add bundleDependencies to package.json
        working-directory: sdks/js
        run: |
          node -e '
          const fs = require("fs");
          const pkg = JSON.parse(fs.readFileSync("package.json", "utf8"));
          const newDep = "@modelcontextprotocol/sdk";
          if (!pkg.bundleDependencies) {
            pkg.bundleDependencies = [newDep];
          } else if (!pkg.bundleDependencies.includes(newDep)) {
            pkg.bundleDependencies.push(newDep);
          }
          fs.writeFileSync("package.json", JSON.stringify(pkg, null, 2) + "\n");
          '

      - name: Publish SDK
        working-directory: sdks/js
        run: npm publish --provenance --access public
